version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    restart: always

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6479:6379"
    restart: always